name: Build and Deploy to GKE

on:
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.GOOGLE_PROJECT_ID}}
  CLUSTER: golang-app-cluster
  CLUSTER_ZONE: asia-southeast2

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login github registry
        run: echo ${{secrets.TOKEN_GITHUB}} | docker login ghcr.io -u adityasuryadi --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/adityasuryadi/golang-app:${{github.sha}} .

      - name: Push image
        run: docker push ghcr.io/adityasuryadi/golang-app:${{github.sha}}

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_KEY }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{env.CLUSTER}}
        location: ${{env.CLUSTER_ZONE}}

    - name: Deploy to GKE
      run: |-
        sed -i -e 's/DOCKER_IMG_TAG/'${{ github.sha }}'/' ./kubernetes/deploy-gke.yaml
        kubectl apply -f ./kubernetes/deploy-gke.yaml