name: Continuous Integration

on:
  push:
    branches:
      - staging

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go mod tidy
      - name: Test with the Go CLI
        run: go test ./test
  

 